### ISSUE TITLE
High Sierra 10.13.6 probook 4530s

### ISSUE THREAD

**Issue by amervelic** [ubihazard/macos-scripts#1]
For years I have installed HS on hp probook 4530s and of course the problems with artifacts and freezing, however, it significantly decreased after calculating KASLR (128). The only system that works as fast as HS in my experience is Mojave, the others are almost unusable. Please use ecenabler.kext for battery indicator. It's an incomparably better experience and easier to maintain.

**Comment by ubihazard** [comment]
I have recently resurrected my ProBook 4530s. I‘ve upgraded CPU to Core i7, increased RAM to 16 GB, changed [Wi-Fi](https://github.com/ubihazard/probook-4x30s#wi-fi) module, and even swapped screen to a 1080p FullHD panel (that last one turned out to be quite a challenge). I don‘t recommend doing it without experience though: this laptop is very hard to work on without breaking something easily.

> For years I have installed HS on hp probook 4530s and of course the problems with artifacts and freezing

In the process of upgrading this laptop, I‘ve actually solved the HD 3000 artifacting problem.

> however, it significantly decreased after calculating KASLR (128)

No, it doesn‘t help, – it just gives a placebo effect. KASLR has nothing to do with HD 3000 glitches. The reason for HD 3000 artifacts is an EC (embedded controller) corruption / misconfiguration between it and the OS: I‘ve seen them happen even on Linux. I‘ve updated my ProBook 4530s [OpenCore repo](https://github.com/ubihazard/probook-4x30s) (actually it applies to all 4x30s series laptops) and [documented my findings](https://github.com/ubihazard/probook-4x30s#hd-3000-graphical-glitches). The provided EFI folder now supports latest macOS Monterey. I have Monterey 12.6.8 installed now and completely glitch-free. (Verified in Unigine Heaven benchmark.) It‘s been couple weeks already and no sign of them returning (unless you are breaking the “rules” – see the linked guide section).

> The only system that works as fast as HS in my experience is Mojave, the others are almost unusable.

Feeling smooth here on Monterey with upgraded CPU: I have [reduced transparency](https://github.com/ubihazard/probook-4x30s#fixing-blur-effects-in-big-sur-and-monterey) enabled with transparent dock. Everything feels responsive even on a 1080p screen.

> Please use ecenabler.kext for battery indicator.

Added it in the latest [EFI folder](https://github.com/ubihazard/probook-4x30s/releases/tag/v1.1), although I personally have no use of it. My battery still needs a replacement.
